" Example Vim configuration.
" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

silent! call pathogen#runtime_append_all_bundles()

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

"set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set mouse=a                       " mouse support

set clipboard=unnamed             " use system clipboard

" UNCOMMENT TO USE
set tabstop=4                    " Global tab width.
set shiftwidth=4                 " And again, related.
set softtabstop=4
set expandtab                    " Use spaces instead of tabs

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
" set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

set list listchars=tab:\ \ ,trail:·

" Or use vividchalk
colorscheme topfunky-light

" set up map leader
let mapleader=","

" use FuzzyFinder
"map <leader>t :FufCoverageFile<cr>
"map <leader>b :FufBuffer<cr>
" nicer colors for popup menu
highlight Pmenu ctermfg=1 ctermbg=4 guibg=grey30

" get rid of search hilights
nmap <silent> <leader>/ :nohlsearch<cr>

" Easy window navigation
nmap <leader>h <C-w><left>
nmap <leader>j <C-w><down>
nmap <leader>k <C-w><up>
nmap <leader>l <C-w><right>

" fugitive
"nmap <leader>gd :Gdiff<cr>
"nmap <leader>gs :Gstatus<cr>
"nmap <leader>gc :Gcommit<cr>

" Controversial...swap colon and semicolon for easier commands
"nnoremap ; :
"nnoremap : ;

"vnoremap ; :
"vnoremap : ;

" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2
set foldlevelstart=20

" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
"autocmd BufNewFile,BufRead *_spec.rb compiler rspec

" :w!! reopens the file as sudo and saves it
cmap w!! %!sudo tee > /dev/null %

" needed for rubyblock
"runtime macros/matchit.vim

" for ctags
nmap <leader>rt :!ctags --extra=+f -R *<CR><CR>
" jump to definition
nmap <leader>d <C-]>
" jump back from definition
nmap <leader>c <C-t>
" open definition in a new vertical split
nmap <leader>s :vsp <CR><C-w>l:exec("tag ".expand("<cword>"))<CR>

"My customizations
"map k <down>
"map j <left>
"map l <right>
"map h <insert>

"set cindent

set directory^=$HOME/.vim_swap   "put all swap files together in one place

"set number                        " Turn on line numbers

" Automatically cd into the directory that the file is in
autocmd BufEnter * execute "chdir ".escape(expand("%:p:h"), ' ')

" Mappings to access buffers (don't use "\p" because a
" delay before pressing "p" would accidentally paste).
" \l       : list buffers
" \b \f \g : go back/forward/last-used
" \1 \2 \3 : go to buffer 1/2/3 etc
"nnoremap <Leader>l :ls<CR>
nnoremap <Leader>b :bp<CR>
nnoremap <Leader>f :bn<CR>
"nnoremap <Leader>g :e#<CR>
nnoremap <Leader>1 :1b<CR>
nnoremap <Leader>2 :2b<CR>
nnoremap <Leader>3 :3b<CR>
nnoremap <Leader>4 :4b<CR>
nnoremap <Leader>5 :5b<CR>
nnoremap <Leader>6 :6b<CR>
nnoremap <Leader>7 :7b<CR>
nnoremap <Leader>8 :8b<CR>
nnoremap <Leader>9 :9b<CR>
nnoremap <Leader>0 :10b<CR>
" It's useful to show the buffer number in the status line.
set laststatus=2 statusline=%02n:%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P

set grepprg=grep\ -nH\ $*

"set foldmethod=marker

" Space will toggle folds
nnoremap <space> za

autocmd! GUIEnter * set vb t_vb=
